version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=python
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=prueba_python
    ports:
      - '5432:5432'